hapi:
  fhir:
    version: R4
    server:
      path: /fhir/*
    rest:
      server-name: schedule-api
      server-version: 1.0.0
      implementation-description: Prototype transactional API for scheduling data
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
vs:
  schedule-source:
    schedule-enabled: false
    upload-schedule: "0 0 11 * * *" # Daily at 11:00 AM Eastern Time
    upload-timezone: America/New_York
    sources:
      - "http://localhost:9090/"
management.endpoints.web:
  exposure:
    include: health, info, refresh
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      function:
        definition: supplyStream;receiveStream
      bindings:
        #        send-out-0:
        #          destination: ints
        #        receive-in-0:
        #          destination: total
        #        accumulate-in-0:
        #          destination: ints
        #        accumulate-out-0:
        #          destination: total
        supplyStream-out-0:
          destination: refresh
        receiveStream-in-0:
          destination: refresh
