version: "3.5"

services:
  db:
    image: library/postgres:13-alpine
    ports:
      - "${VS_DB_PORT:-5432}:${VS_DB_PORT:-5432}"
    environment:
      - POSTGRES_DB=vs
      - POSTGRES_USER=vaccine_schedule
      - POSTGRES_PASSWORD=this_is_not_safe
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
  publisher:
    build:
      context: .
      dockerfile: publisher-application/Dockerfile
    image: vs-publisher
    command: bootRun
    ports:
      # map SR_API_PORT on localhost to the API server in the container
      - "${VS_PUBLISHER_PORT:-9090}:9090"
