server:
  port: 9090
hapi:
  fhir:
    version: R4
    server:
      path: /fhir/*
    rest:
      server-name: schedule-publisher
      server-version: 1.0.0
      implementation-description: Prototype bulk publish API for vaccine schedules
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
publisher:
  base-url: http://localhost:${server.port}
